version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: link-harvester-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000" 
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    env_file: .env

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80" 
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: link-harvester-scheduler
    volumes:
      - .:/var/www/html
    env_file: .env
    depends_on:
      - db
